# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('vote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VotingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('iframe', models.URLField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='votingitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.VotingSession'),
        ),
        migrations.AddField(
            model_name='votecast',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.VotingItem'),
        ),
        migrations.AddField(
            model_name='votecast',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.VotingSession'),
        ),
        migrations.AddField(
            model_name='votecast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='votecast',
            unique_together=set([('session', 'user', 'item')]),
        ),
    ]
