# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_auto_20160330_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingitem',
            name='element',
        ),
        migrations.AddField(
            model_name='votingitem',
            name='element',
            field=models.ManyToManyField(to='booth.VotingElement'),
        ),
    ]
