# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_auto_20160330_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.VotingSession')),
            ],
        ),
        migrations.RemoveField(
            model_name='votingitem',
            name='element',
        ),
        migrations.AddField(
            model_name='votingitem',
            name='element',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booth.VotingElement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingitem',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booth.VotingCategory'),
            preserve_default=False,
        ),
    ]
