# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booth', '0004_auto_20160330_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='votingitem',
            name='category',
        ),
        migrations.AddField(
            model_name='votingelement',
            name='field',
            field=models.CharField(default='ID_ASOC', max_length=200),
        ),
        migrations.AddField(
            model_name='voterelements',
            name='items',
            field=models.ManyToManyField(to='booth.VotingElement'),
        ),
        migrations.AddField(
            model_name='voterelements',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
