# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_auto_20160411_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingitem',
            name='element',
        ),
        migrations.AddField(
            model_name='votecast',
            name='element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booth.VotingElement'),
            preserve_default=False,
        ),
    ]
