# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0006_auto_20160411_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingcategory',
            name='session',
        ),
        migrations.RemoveField(
            model_name='votingfactor',
            name='session',
        ),
        migrations.DeleteModel(
            name='VotingCategory',
        ),
        migrations.DeleteModel(
            name='VotingFactor',
        ),
    ]
