# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0008_votingitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterelements',
            name='sequence',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
