# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0009_voterelements_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingelement',
            name='repr',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
