# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0010_votingelement_repr'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votecast',
            unique_together=set([('session', 'user', 'element', 'item')]),
        ),
    ]
